defaults:
  - llm: ???
  - dataset: ???
  - prompt: ???
  - generation_config: ???
  - _self_

stored_features: attention_diags
split: ${dataset.test_split_name}
batch_size: 1
results_dir: ???
random_seed: ???
