name: trivia_qa
subset: rc.nocontext
path: null
cls_path: hallucinations.config.QaDatasetConfig
test_split_name: validation
max_answer_tokens: 80 # llama-3.1 tokenizer (without special tokens)
target_column_name: answer
